<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
namespace Swiftriver\Core;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for ParserFactory.
 * Generated by PHPUnit on 2010-03-13 at 09:23:18.
 */
class SwiftriverSourceParsingServiceTest extends \PHPUnit_Framework_TestCase {
    /**
     * Include the following files:
     * IParser interface
     */
    protected function setUp() {
        include_once(dirname(__FILE__)."/../../../Setup.php");
    }

    /**
     * Tests that, given a channel configured to use the Test parser,
     * the SiSPS can return a list of content items
     */
    public function testFetchContentFromChannelWithTestParser(){
        $channel = new \Swiftriver\Core\ObjectModel\Channel();
        $channel->type = "Test";
        $service = new \Swiftriver\Core\Modules\SiSPS\SwiftriverSourceParsingService();
        $contentItems = $service->FetchContentFromChannel($channel, null);
        $this->assertEquals(true, is_array($contentItems));
        $this->assertEquals(1, count($contentItems));
        $this->assertEquals("testId", $contentItems[0]->id);
    }
}
?>
